baseurl = "http://blue-jay.github.io/"
languageCode = "en-us"
title = "Blue Jay"
publishdir = "../blue-jay.github.io"

theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
googleAnalytics = "UA-80295457-1"

[params]
# General information
author = "Joseph Spurrier"
description = "Blue Jay is a toolkit written in Go for the web."
copyright = "Released under the MIT license"

# Repository
provider = "GitHub"
repo_url = "https://github.com/blue-jay/blueprint"

version = "0.6-charlie"
logo = "images/bluejaylogo.png"
favicon = "images/favicon.ico"

permalink = "#"

# Custom assets
custom_css = ['stylesheets/global.css', 'stylesheets/colors.css']
custom_js  = []

# Syntax highlighting theme
highlight_css  = ""

[params.palette]
primary = "jayblue"
accent  = "amber"

[params.font]
text = "Ubuntu"
code = "Ubuntu Mono"

[social]
twitter = ""
github  = "blue-jay"

[[menu.main]]
name   = "Toolkit Overview"
url    = "/"
weight = 0

[[menu.main]]
name   = "Structure"
url    = "structure/"
weight = 5

[[menu.main]]
name   = "Configuration"
url    = "configuration/"
weight = 10

[[menu.main]]
name   = "Assets"
url    = "assets/"
weight = 15

[[menu.main]]
name   = "Routing"
url    = "routing/"
weight = 20

[[menu.main]]
name   = "Middleware"
url    = "middleware/"
weight = 30

[[menu.main]]
name   = "Controllers"
url    = "controllers/"
weight = 40

[[menu.main]]
name   = "Models"
url    = "models/"
weight = 50

[[menu.main]]
name   = "Views"
url    = "views/"
weight = 60

[[menu.main]]
name   = "Library"
url    = "library/"
weight = 65

[[menu.main]]
name   = "Jay Overview"
url    = "jay/"
weight = 70

[[menu.main]]
name   = "Find and Replace"
url    = "find-replace/"
weight = 75

[[menu.main]]
name   = "Database Migration"
url    = "database-migration/"
weight = 80

[[menu.main]]
name   = "Code Generation"
url    = "generation/"
weight = 90

[blackfriday]
smartypants	= true
fractions = true
smartDashes = true
plainIDAnchors = true